### PR TITLE
Blocks fix

### PR DESCRIPTION
**Pull request by jbornschein**

### CODE REVIEW

**Comment by jbornschein** [comment]
@dribnet, I'm gonna merge your old fixes; The goal is to make the code run again with the latest blocks/fuel version.

**Comment by dribnet** [comment]
Yes, I just noticed that there's been a release in the last few weeks - probably a good idea to now pin this project to that release and update, etc. Thanks!

**Comment by jbornschein** [comment]
Great, Thnx!

**Comment by dribnet** [comment]
Note I have a lots of more experimental changes in my develop branch:
- ability to load custom datasets (local hdf5 files)
- support for non-square inputs (separate width/height options)
- new "dashboard" output ever 10 epochs
- support for lab colorspace
- updates to sample.py:
  - can set num rows/cols in cli
  - --flat option to "flatten" high dimensional latent space
  - --tight option for tighter spacing
  - cli options to set subdir and filename

Happy to discuss which of these might be useful to merge back to upstream master.

**Pull request merged**
