### PR TITLE
checkpointing changes and updates for latest fuel

### PR DESCRIPTION
**Pull request by dribnet**
I've rounded up a lot of the work by @udibr and others that enhances the checkpointing and updates this codebase to be compatible with the latest versions of blocks and fuel. The main changes are:
- Checkpointing changes: checkpoint subclass, animations at each checkpoint, separate checkpoint subdirectory
- Fuel updates: update for latest fuel interface and README updates for how to download datasets
- Assorted maintenance: README updates, removed unnecessary binarized_sketch file, etc

Happy to continue to contribute if you plan on maintaining this project going forward - I'd love to see grayscale mnist working next.

### CODE REVIEW

**Comment by udibr** [comment]
Please look at https://github.com/udibr/sketch for better usage of Blocks.
I've separated the sampling from the Checkpoint class.
I've used SequenceGenerator class from Blocks to do all the management of the network.
This class also has extensions to handle the attention mechanisem of draw.

**Comment by jbornschein** [comment]
I'll take a more detailed look at your pull-request on the weekend. In general I'm looking forward to merge most of them -- but your PR contains various different aspects and I want to take the time to go through them in detail.

**Comment by jbornschein** [comment]
Sorry that it took me so long to merge this!

But your PR contained various changes and I wanted to cherry-pick only some of them. I'm not so happy with your Checkpointing class -- although I agree that it es very useful to see the currently generated samples while training. For now I will put it into it's own module and not activate it in the main training script.

**Comment by dribnet** [comment]
No worries, glad you found some of that useful.

I'd also be interested in extending draw to cover grayscale mnist, but haven't been able to get that to work yet.  But if that (or color) is also a feature you'd like to see, feel free to open an issue and we can start a discussion on what would be involved.

**Comment by ghost** [comment]
Hi guys. I've got a Torch implementation of DRAW, which I have to use because unfortunately my GPU does not work too well with this implementation.

I'm also working on extending the algorithm to multichannels/animations/text conditioning - I'm training it right now on CGI animations - will let you know how it goes ?

**Comment by jbornschein** [comment]
@AjayTalati 

I'm curious: Is your your Torch implementations noticeable faster (or sower) than the Theano one? Do you think the speedup only applies to your (generation of) GPU?

I guess you had to derive and implement the gradient through the attention mechanism yourself, or is there some mechanism to do this automatically?

@dribnet: Yes, I'm very interested in a multichannel/color version of this. I actually started a branch (multichannel) for this some time ago, but never finished it because I moved on to a different project. Will open a issue for this and we can discuss how to best approach it.

**Comment by ghost** [comment]
Hi Jorg, 

about speed it's hard to tell? I have a friend who tests my code on large dimension/hi-res CGI projects with a box of 4 Titan-X's, and she says it's like lightening, and can do some impressive stuff? 
About calculating the filter banks in the attention mechs - yes unfortunately I had to EVERYTHING with pen and paper, and then code it up using very basic matrix ops. It was hell and the code is very complicated, but fast and efficient, that's the reason I hav'nt made it public - would be too much trouble maintaining it. 

multichannel_yoga_girl

Best regards,

Aj

**Comment by udibr** [comment]
Hi Ajay,
I saw your handwritting on Twitter and it looks amazing! Is it from the same code?
I have a [similar project](https://github.com/udibr/sketch) just for handwriting but yours looks much better.
I also saw that Blocks/Theano somehow consume a lot of my GPU memory (I have GTX980)
I would love to compare your Torch code one for one with Theano code. First to fix my code to be as good as yours and then to see what are the performance differences.
I did some programming in Torch and as a programming language it is a nightmare compared with Python but if the performance is so much better then its time to move...

Thanks, Udi

**Comment by dribnet** [comment]
@jbornschein - I like the series of changes you've made to the code, but did you test running and saving a model after these changes? Initially this didn't seem to want to run against blocks master or stable - but I found a specific blocks commit that did work after rebuilding my hdf5 files, though I still could not `nosetests` to pass against mnist [(you can see my changes for those issues here)](https://github.com/jbornschein/draw/compare/jbornschein:de24bd0...dribnet:8bb4cca).

However, it appears the model runs now only until the first epoch and then seems to get caught in an infinite loop when pickling and crashes with a `RuntimeError: maximum recursion depth exceeded`. I can provide more details or look at this more in the next day or two.

**Comment by ghost** [comment]
@udibr Hi, the 'trick' to getting the handwriting generation to draw realistic is to model the time gap between the times the pen plots in the x,y co-ordinates. I can't remember if Alex Graves does this? But the data to model it is available in the IAM dataset of online handwriting that I used for that network. IIRC I think I just modelled the time gaps between pen plots as something like 10 Gaussians? It was a long time ago :-1: 

I'll talk to the people who I'm working with to see what they say about releasing my code. It's not easy to understand at all - and if I was you I'd sick with Jorg's implementation. Blocks is great, and it's better to have something you understand, than something flash which you don't? Additionally I've made a lot of changes to the original DRAW algorithm e.g. colour and online encoding, which were needed for my inverse graphics work, so it's not really the same as the original paper any more?  

Best regards, Aj

**Comment by jbornschein** [comment]
@dribnet I have the same problem -- Checkpointing crashes with maximum recursion depth exceeded. Sigh... pickling (theano) models... 

For the other issue with `blocks.extras.`: Did you install the http://github.com/mila-udem/blocks-extras package?

**Comment by dribnet** [comment]
For the recursion depth issue I found a [simple workaround](https://github.com/dribnet/draw/commit/97bdb7eb2188e30cc8ddfd98f498f1ab7266d86a) for now that is working well for me, and I've also found a [non-recursive pickler wrapper](http://bugs.python.org/issue2480) I might also try later which would provide a better solution.

Next thing I'm going to look at is why the mnist dataset is [not passing nosetests](https://github.com/jbornschein/draw/commit/8bb4ccab35d1911808944452c56d2602cc2c3801#diff-1d6fbdd6f6a11cf3d9c93c29d4094638). Then I'll confirm that mnist still doesn't produce sensible results on the current codebase and open an issue to tackle that first.

**Comment by dribnet** [comment]
Oh, and I do know about blocks extras, but in the past had some trouble getting it to install correctly. So since it's not currently enabled in the code - and it was hard enough for me to [find a compatible version of blocks](https://github.com/dribnet/draw/commit/4509fb41dd8eaa3bfb632918a549ba17ffd1d109) - it seemed easier for now to [just comment out the unused dependency](https://github.com/dribnet/draw/commit/cc09168aff75b780f8930b36f5001dcbf45fdad2).

**Comment by jbornschein** [comment]
I thought I tried setting some high maximum recursion depth and it didn't work for me -- obviously I made some mistake. I opened #16  for this yesterday.

MNIST and TFD are failing because these datasets are >=0, <=255 -- they need to be normalized/scaled to be between 0 and 1. (opened issue #15 yesterday).

And I guess issue #17 opened by @stas-sl describes the problem why you had to pick a specific blocks version?

**Pull request merged**
